### ISSUE TITLE
Issues with replicating documentation example

### ISSUE THREAD

**Issue by stanleesocca** [briochemc/AIBECS.jl#58]
Hi @briochemc, 

I was going through the AIBECS model with the example provided by the documentation. In the Radiocarbon dating example, I noticed that plotting function was not working as expected: It throws an error whenever I wanted to plot the horizontal slice graph: 

```
plothorizontalslice(age_in_yrs, grd, depth=2000u"m", color=:magma)
ERROR: MethodError: no method matching plot(::AIBECS.HorizontalPlane; color=:magma)
```

Similar error is encountered in the horizontal mean plot. Do you know what when wrong there? 

Thanks

**Comment by briochemc** [comment]
Hi! 

I just tried it locally and it worked fine with Julia v1.5.3 (AIBECS v0.8.3 and Plots v1.10.1). Could it be that you forgot `using Plots`?

**Comment by stanleesocca** [comment]
Issue resolved. Nice. Thanks. 

By, the way great job with this cool package. I was wondering how one can use the CTKAlg algorithm on a PDEs setup to explore 1D water column steady state profile. Any tips on that?

**Comment by briochemc** [comment]
Thanks!

Yes, if you can draft me a grid and circulation of a 1D column that you'd like, then I can add it and you'll be able to run models with it.

FWIW, the goal is to eventually to delegate the solver algorithm part to [DifferentialEquations.jl](https://github.com/SciML/DifferentialEquations.jl) and other packages (like [SIAMFANLEquations.jl](https://github.com/ctkelley/SIAMFANLEquations.jl), which is the "official" Julia version of my CTKAlg, which I adapted from MATLAB's `nsold.m`) for AIBECS v1.
