### ISSUE TITLE
Missing GEOTRACESTools?

### ISSUE THREAD

**Issue by profseth** [briochemc/AIBECS.jl#82]
The documentation for AIBECS suggests that there is a package GEOTRACES tools which contains, among other things, a function 'tracertransect'. Is this defunct?

**Comment by briochemc** [comment]
OK I think I fixed this in https://github.com/JuliaOcean/AIBECS.jl/commit/256f67fc1a84858c24f5672ea85d7b6c553f1d9c. The main issue was that I renamed GEOTRACESTools.jl to GEOTRACES.jl. I pushed an update so the updated docs should be deployed in about half an hour! Please reopenthis issue if this was not properly fixed for you 😃
