### ISSUE TITLE
OCIM2-48L

### ISSUE THREAD

**Issue by profseth** [briochemc/AIBECS.jl#86]
There's a new circulation in town! A recent manuscript describes the OCIM2-48L transport matrix, which in particular seems to do well representing North Pacific circulation (https://doi.org/10.1038/s41467-021-24648-x). The transport matrix is available here (https://figshare.com/articles/dataset/OCIM2-48L_base_state_model_output/14802732).

Maybe AIBECS can include a new grd?

**Comment by briochemc** [comment]
I'll try to add it soon :)

**Comment by briochemc** [comment]
Hi Seth,

I just added it in https://github.com/JuliaOcean/AIBECS.jl/commit/37fec0ee426cb8c6318c053351001239f9946838 (sorry for the delay but as you know I have less time left to develop AIBECS). In an hour or so the new version should be released with it (v0.12). Once it's there could you give it a go and let me know?

```julia
grd, T = OCIM2_48L.load()
```

should give you all you need!

Cheers!
