### ISSUE TITLE
AIBECS precompiling issue 

### ISSUE THREAD

**Issue by zliangocean** [briochemc/AIBECS.jl#95]
I tried to run julia and use AIBECS in a HPC cluster. When I tried to use AIBECS, it failed to precompile and showed the error below:

I am wondering if you have any sense on it and how to solve it?

```julia
julia> using AIBECS
[ Info: Precompiling AIBECS [ace601d6-714c-11e9-04e5-89b7fad23838]
┌ Warning: UnitfulRecipes has been deprecated.
│
│ ```
│ using Unitful, Plots
│ ```
│ should suffice to plot unitful data.
└ @ UnitfulRecipes ~/.julia/packages/UnitfulRecipes/R6doQ/src/UnitfulRecipes.jl:10
ERROR: LoadError: InitError: SystemError: opening file "/julia-1.8.2/share/julia/cert.pem": No such file or directory
```

**Comment by briochemc** [comment]
Ha! Never seen that one... 🤔 

But it looks like a problem with your Julia installation, which should contain the missing `cert.pem` file. 

You can maybe try this ([source](https://github.com/JuliaLang/IJulia.jl/issues/1056#issuecomment-1290338593)):

```sh
sudo wget https://curl.se/ca/cacert.pem -O /usr/share/julia/cert.pem
```

PS: The UnitfulRecipes warning should go away with the latest AIBECS version.

**Comment by zliangocean** [comment]
Thank you so much! It has been solved. The file "cert.pem" is in another directory for some reason.

**Comment by briochemc** [comment]
No worries! Let me know if you need any help with AIBECS 😃
